# compile SDL project from cli like so:
#gcc -o test test.c `sdl-config --cflags --libs`

CC = gcc
RM = rm

# get the proper CFLAGS and LDFLAGS for SDL:
#SDL_CFLAGS := $(shell sdl-config --cflags)
#SDL_LDFLAGS := $(shell sdl-config --libs)

CFLAGS := $(shell sdl-config --cflags)
LDFLAGS := $(shell sdl-config --libs)
LDFLAGS += -lSDL_mixer

TARGET = padsample
OBJS = pad.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS)

clean:
	$(RM) -f $(TARGET)
	$(RM) -f $(OBJS)


